config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  get 'welcome/index'
  resources 'entries'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@entries = Entry.all
	end
	def show
		@entry = Entry.find(params["id"])
	end 
	def create
		entry_params = params["entry"].permit("title", "contents")
 		entry = Entry.create(entry_params)
  		redirect_to(entry_path(entry))
	end
	def edit
		@entry = Entry.find(params["id"])
	end
	def update
  		entry_params = params["entry"].permit("title", "contents")
  		entry = Entry.find(params["id"])
  		entry.update(entry_params)
  		redirect_to(entry_path(entry))
	end
	def destroy
		@entry = Entry.find(params[:id])
		@entry.destroy
		redirect_to(entries_path)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@websites = [
  	  ["http://railsgirls.com", "Rails Girls"],
 	   ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
  	  ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
	  ]
	@entries = Entry.all
  end
  def show
		@Entry = Entry.find(params["id"])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>
<p><%= link_to "Delete this entry", @entry, method: :delete, data: { confirm: "You sure?" } %></p>

app/views/entries/index.html.erb
<% for entry in @entries do %>
    <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
      <p><%= entry.date %></p>
      <p><%= entry.contents %></p>
<% end %>

<%= link_to("New entry", new_entry_path) %>
<p><%= link_to("Back to landing page", welcome_index_path) %></p>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>
<p><%= link_to("Back to landing page", welcome_index_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<body>
  <% for entry in @entries %>
    <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
      <p><%= entry.date %></p>
      <p><%= entry.contents %></p>
  <% end %>
  <%= link_to("New entry", new_entry_path) %>
  <div>
  <h1>Rails help websites</h1>
<% for url, name in @websites %>
  <li><a href="<%= url %>"><%= name %></a></li>
<% end %>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />
</body>